export enum ActivitiesName {
  SUBMIT_INVESTIGATION = 'Submit Investigation',
  REVIEW_APPLICANT_DEPARTMENT = 'Review Applicant Department',
  REVIEW_CUSTOMS_AFFAIRS = 'Review Customs Affairs',
  REVIEW_DEPARTMENT_STATEMENT = 'Review Department Statement',
  REVIEW_GRIEVANCE_STATEMENT = 'Review Grievance Statement',
  REVIEW_DISCIPLINARY_COUNCIL = 'Review Disciplinary Council',
  REVIEW_DISCIPLINARY_COUNCIL_SIGNATURE = 'Review Disciplinary Council Signature',
  REVIEW_FINAL_PRESIDENT_ASSISTANT = 'Review Final President Assistant',
  REVIEW_HUMAN_RESOURCES = 'Review Human Resources',
  REVIEW_LEGAL_AFFAIRS = 'Review Legal Affairs',
  REVIEW_PRESIDENT = 'Review President',
  REVIEW_PRESIDENT_ASSISTANT = 'Review President Assistant',
  SUBMIT_GRIEVANCE_PRESIDENT = 'Submit Grievance President',
  SUBMIT_GRIEVANCE_PRESIDENT_ASSISTANT = 'Submit Grievance President Assistant',
  REVIEW_PENALTY_MODIFICATION = 'Review Penalty Modification',
}
