export enum InvestigationCategory {
  LEGAL_AFFAIRS_INVESTIGATION_RECORD = 1,
  LEGAL_AFFAIRS_HEARING_TRANSCRIPT = 2,
  DISCIPLINARY_COMMITTEE_INVESTIGATION_RECORD = 3,
  DISCIPLINARY_COMMITTEE_HEARING_TRANSCRIPT = 4,
}
