export enum OffenderStatusEnum {
  TERMINATE = 0,
  UNDER_INVESTIGATION = 1,
  REFERRED_TO_THE_ASSISTANT_PRESIDENT = 2,
  REFERRED_TO_THE_ASSISTANT_PRESIDENT_ASSISTANT = 3,
  THE_PENALTY_WAS_IMPOSED = 4,
  SAVED = 5,
  REFERRED_TO_LEGAL_AFFAIRS = 6,
  DELAYED = 11,
  PENALTY_UPDATED = 14, // تم التعديل من التظلم
  UNDER_MODIFICATION = 15,
  PENALTY_MODIFIED = 16, // تم التعديل من طلب تعديل جزاء
}
