export enum OffenderLevels {
  FOURTH_DEGREE_OR_LESS = 1,
  THE_DEGREE_OF_UNDERSECRETARY_TO_THE_FIRST_DEGREE = 2,
  SECOND_DEGREE_OR_LESS = 3,
  THE_DEGREE_OF_UNDERSECRETARY_TO_THE_THIRD_DEGREE = 4,
}
