export enum PenaltySignerTypes {
  MANAGER_DIRECTOR = 1,
  PRESIDENT_ASSISTANT = 2,
  PRESIDENT_ASSISTANT_FOR_CUSTOMS_AFFAIRS_OR_COMMISSIONER = 3,
  PERMANENT_DISCIPLINARY_COUNCIL = 4,
  DISCIPLINARY_COMMITTEE = 5,
}
