export enum StepsName {
  /* ActivityName: Submit Investigation */
  DEPARTMENT_REWORK = 'DEP_REW',
  SAME_CREATOR_REWORK = 'SAME_REW',
  ASSIGNED_TO_USER_REWORK = 'ASSIGN_REW',
  CHIEF_REVIEW = 'CHF_REV',
  CHIEF_REWORK = 'CHF_REW',
  MANAGER_REVIEW = 'MNGR_REV',
  MANAGER_REWORK = 'MNGR_REW',
  /* ActivityName: Review Customs Affairs */
  CUSTOMS_AFFAIRS_MANAGER_REVIEW = 'CA_MNGR_REV',
  CUSTOMS_AFFAIRS_MANAGER_FINAL_REVIEW = 'CA_MNGR_FNL_REV',
  CUSTOMS_AFFAIRS_ASSIGNED_USER = 'CA_ASSIGN',
  CUSTOMS_AFFAIRS_REVIEW = 'CA_REV',
  CUSTOMS_AFFAIRS_DEPARTMENT_REVIEW = 'CA_DEP_REV',
  CUSTOMS_AFFAIRS_REWORK = 'CA_REW',
  CUSTOMS_AFFAIRS_DEPARTMENT_REWORK = 'CA_DEP_REW',
  /* ActivityName: Review Department Statement */
  DEPARTMENT_STATEMENT_REVIEW = 'DEP_STM_REV', // (صادر)
  STATEMENT_OWNER_REVIEW = 'STM_OWNER_REW', // (صادر)
  STATEMENT_DEST_DEPARTMENT = 'STM_DEST_DEP', // (وارد)
  DEPARTMENT_REPLY = 'DEP_REPLY', // (رد)
  /* ActivityName: Review Grievance Statement */
  GRIEVANCE_OWNER_REVIEW = 'GRV_OWN_REV', // (صادر)
  GRIEVANCE_DEPARTMENT_REVIEW = 'GRV_DEP_REV', // (صادر)
  GRIEVANCE_STATEMENT_REVIEW = 'GRV_STM_REV', // (وارد)
  GRIEVANCE_REPLY = 'GRV_REPLY', // (رد)
  /* ActivityName: Review Disciplinary Council */
  REVIEW_DISCIPLINARY_COUNCIL = 'DC_REV',
  /* ActivityName: Review Disciplinary Council Signature */
  REVIEW_DISCIPLINARY_COUNCIL_SIGNATURE = 'DC_SIGN_REV',
  /* ActivityName: Review Final President Assistant */
  PRESIDENT_ASSISTANT_FINAL_REVIEW = 'PA_FNL_REV',
  PRESIDENT_ASSISTANT_FINAL_USER_REVIEW = 'PA_FNL_USER_REV',
  PRESIDENT_ASSISTANT_OFFICE_FINAL_REVIEW = 'PAO_FNL_REV',
  PRESIDENT_ASSISTANT_OFFICE_FINAL_USER_REVIEW = 'PAO_FNL_USER_REV',
  /* ActivityName: Review Human Resources */
  HR_MANAGER_REVIEW = 'HR_MNGR_REV',
  HR_MANAGER_FINAL_REVIEW = 'HR_MNGR_FNL_REV',
  HR_ASSIGN = 'HR_ASSIGN',
  HR_REVIEW = 'HR_REV',
  HR_DEPARTMENT_REV = 'HR_DEP_REV',
  HR_REWORK = 'HR_REW',
  HR_DEPARTMENT_REWORK = 'HR_DEP_REW',
  /* ActivityName: Review Legal Affairs */
  LEGAL_AFFAIRS_PRESIDENT_REWORK = 'LA_PRES_REW',
  LEGAL_AFFAIRS_PRESIDENT_ASSISTANT_REWORK = 'LA_PA_REW',
  LEGAL_AFFAIRS_REVIEW = 'LA_REV',
  LEGAL_AFFAIRS_FINAL_REVIEW = 'LA_FNL_REV',
  INVESTIGATION_CHIEF_REVIEW = 'INV_CHF',
  INVESTIGATOR_REVIEW = 'INV_USR',
  INVESTIGATOR_TEAM_REVIEW = 'INV_LB',
  INVESTIGATION_CREATOR = 'INV_SAME',
  INVESTIGATION_REVIEW = 'INV_REV',
  /* ActivityName: Review President */
  APPLICANT_MANAGER_REWORK = 'PR_APP_MNGR_REW',
  PRESIDENT_REVIEW = 'PR_REV',
  PRESIDENT_USER_REVIEW = 'PR_USR_REV',
  PRESIDENT_OFFICE_REVIEW = 'PO_REV',
  PRESIDENT_OFFICE_USER_REVIEW = 'PO_USR_REV',
  /* ActivityName: Review President Assistant */
  APPLICANT_MANAGER_ASSISTANT_REWORK = 'PA_APP_MNGR_REW',
  PRESIDENT_ASSISTANT_REVIEW = 'PA_REV',
  PRESIDENT_ASSISTANT_USER_REVIEW = 'PA_USR_REV',
  PRESIDENT_ASSISTANT_OFFICE_REVIEW = 'PAO_REV',
  PRESIDENT_ASSISTANT_OFFICE_USER_REVIEW = 'PAO_USR_REV',
}
