export enum SystemPenalties {
  REFERRAL_TO_PRESIDENT = 1,
  REFERRAL_TO_PRESIDENT_ASSISTANT = 2,
  TERMINATE = 3,
  REFERRAL_TO_DISCIPLINARY_COUNCIL = 4,
  REFERRAL_TO_PERMANENT_DISCIPLINARY_COUNCIL = 5,
  SAVE = 6,
}
