export const AppPermissions = {
  MANAGE_INTERNAL_USERS: 'MANAGE_INTERNAL_USERS',
  MANAGE_PENALTY: 'MANAGE_PENALTY',
  MANAGE_VIOLATION_CLASSIFICATION: 'MANAGE_VIOLATION_CLASSIFICATION',
  MANAGE_SERVICES_DATA: 'MANAGE_SERVICES_DATA',
  MANAGE_TEAMS: 'MANAGE_TEAMS',
  MANAGE_LOCALIZATION: 'MANAGE_LOCALIZATION',
  MANAGE_JOB_TITLES: 'MANAGE_JOB_TITLES',
  ADMIN_ADD_USER: 'ADMIN_ADD_USER',
  ADMIN_ADD_OU: 'ADMIN_ADD_OU',
  MANAGE_VIOLATION_TYPE: 'MANAGE_VIOLATION_TYPE',
  ADMIN_EDIT_OU: 'ADMIN_EDIT_OU',
  ADMIN_EDIT_USER: 'ADMIN_EDIT_USER',
  MANAGE_MENU_ITEM: 'MANAGE_MENU_ITEM',
  MANAGE_VACATIONS_DATE: 'MANAGE_VACATIONS_DATE',
  MANAGE_ADMIN_LOOKUP: 'MANAGE_ADMIN_LOOKUP',
  MANAGE_EMAIL_TEMPLATE: 'MANAGE_EMAIL_TEMPLATE',
  MANAGE_PERMISSION_ROLE: 'MANAGE_PERMISSION_ROLE',
  MANAGE_ORGANIZATION_UNIT: 'MANAGE_ORGANIZATION_UNIT',
  GUIDE_PANEL: 'GUIDE_PANEL',
  MANAGE_OFFENDER_VIOLATION: 'MANAGE_OFFENDER_VIOLATION',
};

export type AppPermissionsType = typeof AppPermissions;
