export const AppRoutes = {
  LOGIN: 'login',
  HOME: 'home',
  ADMINISTRATION: 'administration',
  LOCALIZATION: 'localization',
  INTERNAL_USER: 'internal-user',
  PENALTY: 'penalty',
  VIOLATION_CLASSIFICATION: 'violation-classification',
  VIOLATION_TYPE: 'violation-type',
  TEAM: 'team',
  JOB_TITLE: 'job-title',
  PERMISSION_ROLE: 'permission-role',
  BROKER_COMPANY: 'broker-company',
  ORGANIZATION_UNIT: 'organization-unit',
  MAWARED_DEPARTMENT: 'mawared-department',
  MAWARED_EMPLOYEE: 'mawared-employee',
  BROKER: 'broker',
  SERVICES: 'services',
  SERVICE_STEPS: 'service-steps',
  EMAIL_TEMPLATE: 'email-template',
  GLOBAL_SETTING: 'global-setting',
  FILE_TYPE: 'file-type',
  MAIN: 'main',
  ELECTRONIC_SERVICES: 'electronic-services',
  INVESTIGATION: 'investigation',
  USER_INBOX: 'user-inbox',
  VIOLATION_PENALTY: 'violation-penalty',
};
