export const AppIcons = {
  RELOAD: 'reload',
  DOTS_CIRCLE: 'dots-circle',
  TRANSLATE: 'translate',
  SETTINGS: 'cog',
  PLUS: 'plus',
  CLOSE: 'close-circle',
  EDIT: 'pencil',
  VIEW: 'eye',
  DELETE: 'delete',
  FILTER: 'filter',
  LOGOUT: 'logout',
  ACCOUNT_EDIT: 'account-edit',
  FILTER_OUTLINE: 'filter-outline',
  TEAM: 'account-group',
  FILTER_REMOVE: 'filter-remove',
  VALID_FORM: 'check',
  INVALID_FORM: 'alert-circle-outline',
  INTERNAL_USER: 'account',
  MORE_DETAILS: 'information-outline',
  JOB_TITLE: 'badge-account-horizontal',
  PENALTY: 'gavel',
  CANCEL: 'cancel',
  TABLE_CANCEL: 'table-cancel',
  BOOK_CANCEL: 'book-cancel',
  BOOK_CANCEL_OUTLINE: 'book-cancel-outline',
  PERMISSIONS_LIST: 'format-list-checks',
  BROKER_COMPANY: 'domain',
  HOME_GROUP: 'home-group',
  SITE_MAP: 'sitemap',
  SITE_MAP_OUTLINE: 'sitemap-outline',
  MAWARED_DEPARTMENT: 'select-group',
  RESOURCES_CASE: 'briefcase',
  BROKER: 'account-tie-outline',
  USERPREFERENCES: 'account-star-outline',
};

export type AppIconsType = typeof AppIcons;
