export const EndPoints = {
  BASE_URL: '',
  INFO: '/auth/login/info',
  LOCALIZATION: '/entity/localization',
  AUTH: '/auth/internal/login',
  VALIDATE_TOKEN: '/auth/validate-token',
  PERMISSION: '/entity/permission',
  INTERNAL_USER: '/entity/internal/user',
  USER_PREFERENCES: '/entity/user-preferences/internal-user-id',
  USER_PERMISSION: '/entity/internal-user-permission',
  TEAM: '/entity/baw/team',
  PENALTY: '/entity/penalty',
  VIOLATION_CLASSIFICATION: '/entity/violation-classification',
  VIOLATION_TYPE: '/entity/violation-type',
  JOB_TITLE: '/entity/job-title',
  PERMISSION_ROLE: '/entity/permission-role',
  ORGANIZATION_UNIT: '/entity/organization-unit',
  MAWARED_DEPARTMENT: '/entity/mawared-department',
  MAWARED_EMPLOYEE: '/entity/mawared-employee',
  SERVICES: '/entity/services',
  SERVICE_STEPS: '/entity/service-steps',
  EMAIL_TEMPLATE: '/entity/email-template',
  GLOBAL_SETTING: '/admin/global-setting',
  FILE_TYPE: '/admin/global-setting/file-types',
  INVESTIGATION: '/investigation-case',
  USER_INBOX: '/inbox/user',
  TEAM_INBOX: '/inbox/team',
  VIOLATION_PENALTY: '/entity/violation-penalty',
  LEGAL_RULE: '/entity/legal-rule',
  ATTACHMENT_TYPE: '/entity/attachment-type',
  INTERNAL_USER_OU: '/entity/internal-user-ou',
  VIOLATION: 'entity/violation',
  REFRESH_CACHE: '/admin/config/refresh-cache',
  OFFENDER: '/entity/offender',
  OFFENDER_VIOLATION: '/entity/offender-violation',
  GUIDE_PANEL: '/entity/violation-penalty/guide-panel',
  WITNESS: '/entity/witness',
  PENALTY_DECISION: '/entity/penalty-decision',
  SITUATION_SEARCH: '/entity/offender-violation/situation-search',
  USER_TEAM: '/entity/baw/team/user-teams',
  CLEARING_AGENT: '/entity/clearing-agent',
  CLEARING_AGENCY: '/entity/clearing-agency',
  SUSPENDED_EMPLOYEE: '/entity/suspended-employee',
  RELEASE_BULK: '/inbox/task/return/bulk',
};

export type EndpointsType = typeof EndPoints;
