export const MenuIdes = {
  ADMINISTRATION: 1,
  LOCALIZATION: 2,
  INTERNAL_USER: 3,
  JOB_TITLE: 4,
  VIOLATION_CLASSIFICATION: 5,
  VIOLATION_TYPE: 6,
  PENALTY: 7,
  TEAM: 8,
  PERMISSION_ROLE: 9,
  BROKER_COMPANY: 10,
};
